/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

//package javaapplication1;
package packages;
import java.awt.Container;
import java.awt.Font;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.io.File;
import java.io.IOException;
import java.util.Vector;

import javax.swing.DefaultListModel;
import javax.swing.JButton;
import javax.swing.JDialog;
import javax.swing.JLabel;
import javax.swing.JPanel;
import javax.swing.JTextField;
import javax.swing.UIManager;
import javax.swing.table.DefaultTableModel;

import packages.*;


/**
 *
 * @author AndySheng
 */
public class InterfaceMain extends javax.swing.JFrame implements ActionListener{

    /**
     * Creates new form NewJFrame
     */
	
	
	public ClientSocket client;
	private int r, c;     //点击事件的行列
	public String[][] stutable,exptable;
	
	
    public InterfaceMain(ClientSocket c) {
        try {  
        	   client = c;
	           UIManager.setLookAndFeel(//关键句1  
	           UIManager.getSystemLookAndFeelClassName());//关键句2  
	       } catch (Exception qe) {  
	           qe.printStackTrace();  
     } 
        initComponents();
        int x =(((int)java.awt.Toolkit.getDefaultToolkit().getScreenSize().width) - this.getWidth())/2;
        int y = (((int)java.awt.Toolkit.getDefaultToolkit().getScreenSize().height) - this.getHeight())/2; 
        this.setLocation(x,y);
        this.setVisible(true);
        interfaceWaiting = new DialogWaiting(this,true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        classNum = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        stuTable = new javax.swing.JTable();
        mainPan = new javax.swing.JPanel();
        expPan = new javax.swing.JPanel();
        stuName = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jMenuBar1 = new javax.swing.JMenuBar();
        funcButton = new javax.swing.JMenu();
        func1 = new javax.swing.JMenuItem();
        func2 = new javax.swing.JMenuItem();
        jSeparator1 = new javax.swing.JPopupMenu.Separator();
        func3 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "选择学生", javax.swing.border.TitledBorder.LEADING, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("微软雅黑 Light", 0, 14), java.awt.Color.black)); // NOI18N

        classNum.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        classNum.setText("单击来输入班级");
        classNum.setToolTipText("单击来输入班级");
        classNum.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        classNum.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        classNum.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                try {
					classNumMouseClicked(evt);
				} catch (Exception e) {
					// TODO Auto-generated catch block
					e.printStackTrace();
				}
            }
        });

        jScrollPane1.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        stuTable.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        stuTable.setModel(new javax.swing.table.DefaultTableModel(
            new String [][] {
//                {null, null},
//                {null, null},
//                {null, null},
//                {null, null},
//                {null, null},
//                {null, null},
//                {null, null},
//                {null, null},
//                {null, null},
//                {null, null},
//                {null, null},
//                {null, null},
//                {null, null},
//                {null, null},
//                {null, null},
//                {null, null}
            },
            new String [] {
                "学号", "姓名"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        stuTable.setRowHeight(20);
        stuTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                try {
					stuTableMouseClicked(evt);
				} catch (Exception e) {
					// TODO Auto-generated catch block
					e.printStackTrace();
				}
            }
        });
        jScrollPane1.setViewportView(stuTable);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 197, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                .addComponent(classNum, javax.swing.GroupLayout.DEFAULT_SIZE, 197, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(classNum, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(18, 18, 18)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 489, Short.MAX_VALUE)
                    .addContainerGap()))
        );

        classNum.getAccessibleContext().setAccessibleDescription("单击来输入班级");

        mainPan.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "实验信息", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("微软雅黑 Light", 0, 14), java.awt.Color.black)); // NOI18N

        stuName.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        stuName.setText("xx学生");
        stuName.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
             new String [][] {
//                {null, null, null, null},
//                {null, null, null, null},
//                {null, null, null, null},
//                {null, null, null, null}
            },
            new String [] {
                "实验名字", "实验状态", "实验时间", "实验成绩"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                    false, false
                };
            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
                
            }
            
            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return false;
            }
            
        });
        jScrollPane3.setViewportView(jTable1);
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                try {
                	jTable1MouseClicked(evt);
				} catch (Exception e) {
					// TODO Auto-generated catch block
					e.printStackTrace();
				}
            }
        });
      

        javax.swing.GroupLayout expPanLayout = new javax.swing.GroupLayout(expPan);
        expPan.setLayout(expPanLayout);
        expPanLayout.setHorizontalGroup(
            expPanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(expPanLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane3)
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, expPanLayout.createSequentialGroup()
                .addContainerGap(82, Short.MAX_VALUE)
                .addComponent(stuName, javax.swing.GroupLayout.PREFERRED_SIZE, 365, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(101, 101, 101))
        );
        expPanLayout.setVerticalGroup(
            expPanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, expPanLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(stuName, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 26, Short.MAX_VALUE)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 500, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout mainPanLayout = new javax.swing.GroupLayout(mainPan);
        mainPan.setLayout(mainPanLayout);
        mainPanLayout.setHorizontalGroup(
            mainPanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(mainPanLayout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(expPan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(51, Short.MAX_VALUE))
        );
        mainPanLayout.setVerticalGroup(
            mainPanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(mainPanLayout.createSequentialGroup()
                .addComponent(expPan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        funcButton.setText("功能键");

        func1.setText("新建实验");
		func1.addActionListener(this);
        funcButton.add(func1);
        
        func2.setText("修改成绩");
		func2.addActionListener(this);
        //funcButton.add(func2);
        funcButton.add(jSeparator1);

        func3.setText("退出");
		func3.addActionListener(this);
        funcButton.add(func3);


        
        jMenuBar1.add(funcButton);
        funcButton.getAccessibleContext().setAccessibleName("");

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(mainPan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(mainPan, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>                        

    private void stuTableMouseClicked(java.awt.event.MouseEvent evt) throws Exception {                                      
        // TODO add your handling code here
    	
    	//、、、、、、、、、、、、、、选中学生后的代码写在这里
    	if(evt.getClickCount()<2)
    		return;
        r = stuTable.rowAtPoint(evt.getPoint());
        c = stuTable.columnAtPoint(evt.getPoint());
    	System.out.println("选中学生号为"+stuTable.getValueAt(r, c));
    	stuName.setText((String) stuTable.getValueAt(r, 1));
    	stuNum = (String) stuTable.getValueAt(r, 0);
    	client.send("020");
    	client.send(stuNum);
    	this.setWaiting(true);
    	 new Thread(new Runnable(){

     		@Override
     		public void run() {
     			//temp.InterfaceShow();
     			while(waitingSignal);

     			
     			interfaceWaiting.setVisible(false);
     			if(expInfo == null)
     				return;
     			DefaultTableModel model = (DefaultTableModel)jTable1.getModel();
     			System.out.println(model.getRowCount());
     			int rowNum = model.getRowCount();
     			for(int i = 0; i<=rowNum - 1; i++){
     				System.out.println("删除"+model.getValueAt(0, 0));
     				model.removeRow(0);
     			}
     				
     			for(int i = 0; i<=expInfo.size()-1; i++)
     				model.addRow((String[])expInfo.elementAt(i));
     			
     			jScrollPane1.setVisible(false);
     			jScrollPane1.setVisible(true);
     			//temp.dispose();
     		}}).start();
    	   interfaceWaiting.reSetLocation(this);
           interfaceWaiting.setVisible(true);
           mainPan.setVisible(false);
           mainPan.setVisible(true);
    }                                     
     public void updateGrade(String expName,String grade)
     {
    	 String[] a = new String[6];
    	 int i =0;
    	 for(; i<=expInfo.size()-1; i++){
    		 a = (String[]) expInfo.elementAt(i);
    		 if(expName.equals(a[0])){
    			 break;
    		 }
    	 }
    	 a[3] = grade;
    	 expInfo.removeElementAt(i);	
    	 expInfo.insertElementAt(a,i);
    	 DefaultTableModel model = (DefaultTableModel)jTable1.getModel();
			System.out.println(model.getRowCount());
			int rowNum = model.getRowCount();
			for(int j = 0; j<=rowNum - 1; j++){
				System.out.println("删除"+model.getValueAt(0, 0));
				model.removeRow(0);
			}
				
			for(int l = 0; l<=expInfo.size()-1; l++)
				model.addRow((String[])expInfo.elementAt(l));
	           mainPan.setVisible(false);
	           mainPan.setVisible(true);
    	 
     }
    private void classNumMouseClicked(java.awt.event.MouseEvent evt) throws Exception {                                      
        // TODO add your handling code here:
        System.out.println("输入班级");
        waitingSignal = true;
        client.send("016");
        String classnum = new InputClassNumber().getClassNumber();
        classNum.setText(classnum+"班");
        classNum.setToolTipText(classnum+"班");
        client.send(classnum);
       // stopWaiting.
        new Thread(new Runnable(){

    		@Override
    		public void run() {
    			//temp.InterfaceShow();
    			while(waitingSignal);

    			
    			interfaceWaiting.setVisible(false);
    			if(students == null)
    				return;
    			DefaultTableModel expModel = (DefaultTableModel)jTable1.getModel();
    			System.out.println(expModel.getRowCount());
    			int expRow = expModel.getRowCount();
    			for(int i = 0; i<=expRow - 1; i++){
    				System.out.println("删除"+expModel.getValueAt(0, 0));
    				expModel.removeRow(0);
    			}
    			stuName.setText("");
    			
    			DefaultTableModel model = (DefaultTableModel)stuTable.getModel();
    			System.out.println(model.getRowCount());
    			int rowNum = model.getRowCount();
    			for(int i = 0; i<=rowNum - 1; i++){
    				System.out.println("删除"+model.getValueAt(0, 0));
    				model.removeRow(0);
    			}
    				
    			for(int i = 0; i<=students.size()-1; i++)
    				model.addRow((String[])students.elementAt(i));
    			
    			jScrollPane1.setVisible(false);
    			jScrollPane1.setVisible(true);
    			//temp.dispose();
    		}}).start();
        interfaceWaiting.reSetLocation(this);
        interfaceWaiting.setVisible(true);
        mainPan.setVisible(false);
        mainPan.setVisible(true);
        
        System.out.println("请求班级");
    } 
    private void jTable1MouseClicked(java.awt.event.MouseEvent evt){
    	if(evt.getClickCount()<2)
    		return;
    	int row = jTable1.rowAtPoint(evt.getPoint());
    	//-------------下面要改-----------//
    	String singleExpInfo[] = new String[6]; 
    	singleExpInfo[0] = ((String[])expInfo.elementAt(row))[0];
    	singleExpInfo[1] = ((String[])expInfo.elementAt(row))[1];
    	singleExpInfo[2] = ((String[])expInfo.elementAt(row))[3];				
    	singleExpInfo[3] = ((String[])expInfo.elementAt(row))[2];
    	singleExpInfo[4] = ((String[])expInfo.elementAt(row))[4];
    	singleExpInfo[5] = stuNum;
    	String p = stuNum +"\\experiments\\"+singleExpInfo[0];
    	new InterfaceExp(singleExpInfo,p,client,this);
    }
	public void actionPerformed(ActionEvent e) 
	{
		if(e.getActionCommand() == "新建实验")
		{
			try {
				if(new File("temp").exists())
					new DeleteFile("temp");
				new File("temp").mkdirs();
			} catch (IOException e1) {
				// TODO Auto-generated catch block
				e1.printStackTrace();
			}
			new NewExp(client);
		}
		else if(e.getActionCommand() == "修改成绩")
		{
			new InterfaceModify();
		}
		else if(e.getActionCommand() == "退出")
		{
			System.exit(0);
		}
	
	}
	
   
    
	public class InterfaceModify implements ActionListener
	{
		String changedata = new String();
		private JDialog mainDialog;
		private JTextField account;
		private JTextField expname;
		private JTextField grade;
		public InterfaceModify() 
		{
		JPanel Pan = new JPanel();
		mainDialog = new JDialog();
		mainDialog.setSize(300, 200);
		Container container = mainDialog.getContentPane();
		container.setLayout(null);
		
		JLabel label1 = new JLabel("学号");
		JLabel label2 = new JLabel("实验名");
		JLabel label3 = new JLabel("成绩");
		label1.setFont(new Font("宋体",Font.PLAIN,18));
		label2.setFont(new Font("宋体",Font.PLAIN,18));
		label3.setFont(new Font("宋体",Font.PLAIN,18));
		Pan.add(label1);
		Pan.add(label2);
		Pan.add(label3);
		Pan.setBounds(50, 0, 50, 100);
		Pan.setVisible(true);
		container.add(Pan);
		
		Pan = new JPanel();
		account = new JTextField(15);
		expname = new JTextField(15);
		grade = new JTextField(15);
		Pan.add(account);
		Pan.add(expname);
		Pan.add(grade);
		Pan.setBounds(100, 0, 150, 100);
		Pan.setVisible(true);
		container.add(Pan);
		
		Pan = new JPanel();
		JButton buttonOk = new JButton("确定");
		buttonOk.addActionListener(this);
		JButton buttonCancel = new JButton("取消");
		buttonCancel.addActionListener(this);
		Pan.add(buttonOk);
		Pan.add(buttonCancel);
		Pan.setBounds(0, 100, 300, 50);
		Pan.setVisible(true);
		container.add(Pan);
		
		
		
		mainDialog.setTitle("请输入学生的实验信息");
		mainDialog.setResizable(false);
		mainDialog.setModal(true);
		mainDialog.setLocation(500, 300);
		mainDialog.setDefaultCloseOperation(JDialog.DISPOSE_ON_CLOSE);
		mainDialog.setVisible(true);
		}
		public void actionPerformed(ActionEvent e)
		{
			if(e.getActionCommand() == "确定")
			{
				try{
					client.send("013");
					System.out.println("013");
				}catch (Exception e1) {}
				String[] changeGrade = {account.getText(),expname.getText(),grade.getText()};
				try 
				{
					client.send(changeGrade);
				} catch (Exception e1) {}
				try {
					changedata = client.receiveStr();
					System.out.print(changedata);
				} catch (Exception e1) {
					// TODO Auto-generated catch block
					e1.printStackTrace();
				}
				if (changedata.equals ("014"))
				{
					new MessageBox("修改成功","");
				}
				else if(changedata.equals ("015"))
				{
					new MessageBox("修改失败","");
				}
			}
			else if(e.getActionCommand() == "取消")
			{
				mainDialog.setVisible(false);
				mainDialog.dispose();
			}
			
		}
		
		
	}
    /**
     * @param args the command line arguments
     */   
    public static void main(String args[]) {
    }

    public void setWaiting(boolean status)
    {
    	waitingSignal = status;
    }
    public void setStudents(Vector s)
    {
    	students = s;
    }
    public void setExpInfo(Vector e)
    {
    	expInfo = e;
    }
    
    
    
    private Vector expInfo;
    private Vector students;
    private boolean waitingSignal;
    public String stuNum; //提取学生学号以便修改实验成绩提交至服务端
    private DialogWaiting interfaceWaiting;
    // Variables declaration - do not modify                     
    public javax.swing.JLabel classNum;
    public javax.swing.JPanel expPan;
    public javax.swing.JMenuItem func1;
    public javax.swing.JMenuItem func2;
    public javax.swing.JMenuItem func3;
    public javax.swing.JMenu funcButton;
    public javax.swing.JMenuBar jMenuBar1;
    public javax.swing.JPanel jPanel1;
    public javax.swing.JScrollPane jScrollPane1;
    public javax.swing.JScrollPane jScrollPane3;
    public javax.swing.JPopupMenu.Separator jSeparator1;
    public javax.swing.JTable jTable1;
    public javax.swing.JPanel mainPan;
    public javax.swing.JLabel stuName;
    public javax.swing.JTable stuTable;
    // End of variables declaration                   
}
