package packages;

import java.awt.Toolkit;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.io.File;
import java.io.FileNotFoundException;
import java.io.FileReader;
import java.io.IOException;
import java.util.Vector;
import java.util.regex.Matcher;
import java.util.regex.Pattern;

import javax.swing.DefaultListModel;
import javax.swing.JFrame;
import javax.swing.JLabel;
import javax.swing.JMenuItem;
import javax.swing.UIManager;
import javax.swing.table.DefaultTableModel;
/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author AndySheng
 */
public class InterfaceMain extends javax.swing.JFrame implements ActionListener {

    /**
     * Creates new form NewJFrame
     */
    public InterfaceMain(ClientSocket c,PersonalInfo p,Vector exps,Vector hist) throws Exception {

    	try {  
	           UIManager.setLookAndFeel(//关键句1  
	           UIManager.getSystemLookAndFeelClassName());//关键句2  
	       } catch (Exception qe) {  
	           qe.printStackTrace();  
	    } 
    	if(exps != null){
    		expInfoV = exps;
    	}
    	else
    		expInfo = null;
    	//expHistory = hist;
    	expHistory = hist;
    	client = c;
    	personalInfo = p;
    	shudian = new expInfo().getShudian();
        initComponents();
        int x =(((int)java.awt.Toolkit.getDefaultToolkit().getScreenSize().width) - this.getWidth())/2;
        int y = (((int)java.awt.Toolkit.getDefaultToolkit().getScreenSize().height) - this.getHeight())/2; 
        this.setLocation(x,y);
        this.setVisible(true);
    	System.out.println(expInfo.length+"----"+expHistory.size());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {
    	expInfo = new String[expInfoV.size()][4];
    	for(int i = 0; i<=expInfoV.size()-1; i++){
			expInfo[i][0] = ((String[])expInfoV.elementAt(i))[0];//实验名
			expInfo[i][1] = ((String[])expInfoV.elementAt(i))[1];//实验完成情况
			//System.out.print(((String[])exps.elementAt(i))[3]);
			expInfo[i][3] = ((String[])expInfoV.elementAt(i))[2];
			expInfo[i][2] = ((String[])expInfoV.elementAt(i))[3];//成绩
			//expInfo[i][4] = ((String[])expInfoV.elementAt(i))[4];
		}
    	
    	
    	
    	
    	
    	
        jMenuItem5 = new javax.swing.JMenuItem();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        pic = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        expTable = new javax.swing.JTable();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        modify = new javax.swing.JMenuItem();
        jSeparator1 = new javax.swing.JPopupMenu.Separator();
        exit = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        jMenu4 = new javax.swing.JMenu();
        jMenu3 = new javax.swing.JMenu();
        seeHistory = new javax.swing.JMenuItem();
        about = new javax.swing.JMenuItem();

        jMenuItem5.setText("jMenuItem5");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createTitledBorder(null, "个人资料", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("微软雅黑 Light", 0, 14)))); // NOI18N

        pic.setText("");
        pic.setIcon(new javax.swing.ImageIcon(Toolkit.getDefaultToolkit().createImage(personalInfo.getNumber()+"\\me.jpg")));
        
        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "基础信息", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("微软雅黑 Light", 0, 12))); // NOI18N

        jLabel6.setFont(new java.awt.Font("宋体", 0, 14)); // NOI18N
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel6.setText(personalInfo.getNumber());

        jLabel5.setFont(new java.awt.Font("宋体", 0, 14)); // NOI18N
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel5.setText(personalInfo.getName());

        jLabel3.setFont(new java.awt.Font("宋体", 0, 14)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel3.setText("学号：");

        jLabel1.setFont(new java.awt.Font("宋体", 0, 14)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel1.setText(personalInfo.getClas());

        jLabel4.setFont(new java.awt.Font("宋体", 0, 14)); // NOI18N
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel4.setText("姓名：");

        jLabel2.setFont(new java.awt.Font("宋体", 0, 14)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel2.setText("班级：");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(7, 7, 7)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(27, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
                jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel2Layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addContainerGap())
                .addGroup(jPanel2Layout.createSequentialGroup()
                    .addGap(26, 26, 26)
                    .addComponent(pic, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            );
            jPanel2Layout.setVerticalGroup(
                jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel2Layout.createSequentialGroup()
                    .addComponent(pic, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 13, Short.MAX_VALUE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(125, 125, 125))
            );

        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "实验信息", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("微软雅黑 Light", 0, 14))); // NOI18N

        expTable.setModel(new javax.swing.table.DefaultTableModel(
        		/*new Object [][]={
                {"1", null, null, null},
                {"2", null, null, null},
                {"3", null, null, null},
                {"4", null, null, null}
            }*/
        	expInfo,
            new String [] {
                "实验名称", "实验状态", "实验成绩", "实验时间"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        expTable.setRowHeight(25);
        expTable.setToolTipText("双击查看详细信息");
        expTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                expTableMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(expTable);

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 384, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(78, 78, 78))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addComponent(jScrollPane1)
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(42, 42, 42)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, 415, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        jMenu1.setText("功能键");

        modify.setText("修改个人资料");
        modify.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                modifyMouseClicked(evt);
            }
        });
        modify.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                modifyActionPerformed(evt);
            }
        });
        jMenu1.add(modify);
        jMenu1.add(jSeparator1);

        exit.setText("退出");
        exit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                exitMouseClicked(evt);
            }
        });
        exit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
            	exitActionPerformed(evt);
            }
        });
        jMenu1.add(exit);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("进行实验");

        jMenu4.setText("数电实验");
        jMenu2.add(jMenu4);

        
        for(int i = 0; i<=shudian.size()-1; i++){
			JMenuItem dig = new JMenuItem(((String[])shudian.elementAt(i))[0]);
			dig.addActionListener(this);
			jMenu4.add(dig);
		}
        
        jMenuBar1.add(jMenu2);

        jMenu3.setText("查看");

        seeHistory.setText("历史记录");
    
        seeHistory.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
            	seeHistoryActionPerformed(evt);
            }
        });
        jMenu3.add(seeHistory);

        about.setText("关于");
        about.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
            	exitActionPerformed(evt);
            }
        });
        jMenu3.add(about);

        jMenuBar1.add(jMenu3);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>                        
//    public void doneExp(String[] exp)
//    {
//    	boolean flag = false;
//    	String[][] temp = null; 
//    	for(int i = 0; i<=expInfo.length-1; i++)
//    		if(expInfo[i][0].equals(exp[0])){
//    			flag= true;
//    			break;
//    		}
//    	if(flag)
//    		temp = new String[expInfo.length][4];
//    	else
//    		temp = new String[expInfo.length+1][4];
//    	for(int i = 0; i<=expInfo.length-1; i++){
//    		if(expInfo[i][0].equals(exp[0])){
//    			temp[i][0] = exp[0];
//    			temp[i][1] = exp[1];
//    			temp[i][2] = exp[2];
//    			temp[i][3] =  exp[3];
//    			System.out.println("重复");
//    		}
//    		else{
//    			temp[i] = expInfo[i];
//    		}
//    	}
//    	if(!flag)
//    		temp[temp.length-1] = exp;
//    	expInfo = new String[temp.length][4];
//    	expInfo = temp;
//	  	
//		expHistory.addElement(exp);
//		expTable.repaint();
//		System.out.println(" doneExp");
//		
//    } 
    public void doneExp(String[] exp)
    {
    	System.out.println("进入doneExp");
    	for(int i = 0; i<=expInfoV.size()-1; i++){
    		String[] tmp = (String[])expInfoV.elementAt(i);
    		if(tmp[0].equals(exp[0])){
    			System.out.println("删除"+((String[])expInfoV.elementAt(i))[0]);
    			expInfoV.removeElementAt(i);
    			break;
    		}
    	}
    	expInfoV.addElement(exp);
    	expHistory.addElement(exp);
    	System.out.println("输出expInfoV");
    	for(int i =0; i<=expInfoV.size()-1; i++)
    		System.out.println(((String[])expInfoV.elementAt(i))[0]);
    	
    	
    	sync();
    }
    private void modifyActionPerformed(java.awt.event.ActionEvent evt) {                                       
    	InfoModify infoModify = new InfoModify(personalInfo);
		personalInfo = infoModify.getPersonalInfo();
		String[] newInfo = new String[4];
		final JFrame temp = this;
		new Runnable(){

			@Override
			public void run() {
				// TODO Auto-generated method stub
				jLabel6.setText(personalInfo.getNumber());
				jLabel5.setText(personalInfo.getName());
				jLabel1.setText(personalInfo.getClas());
				pic.setIcon(new javax.swing.ImageIcon(Toolkit.getDefaultToolkit().createImage(personalInfo.getNumber()+"\\me.jpg")));
				jLabel6.setText(personalInfo.getNumber());
				temp.repaint();
				System.out.print("done");
			}}.run();
		newInfo[0] = personalInfo.getName();
		newInfo[1] = personalInfo.getClas();
		newInfo[2] = personalInfo.getNumber();
		newInfo[3] = personalInfo.getPassword();
		try {
			client.send("005");
			client.send(newInfo);
			client.sendFile(personalInfo.getNumber()+"\\me.jpg");
		} catch (Exception e1) {
			// TODO Auto-generated catch block
			e1.printStackTrace();
		}
    }                                      

    private void modifyMouseClicked(java.awt.event.MouseEvent evt) {                                    
    	new InfoModify(personalInfo);
    }                                   
    private void exitActionPerformed(java.awt.event.ActionEvent evt) {                                       
    	System.exit(0);
    }    
    private void exitMouseClicked(java.awt.event.MouseEvent evt) {                                  
        System.exit(0);
    }                                 
    private void seeHistoryActionPerformed(java.awt.event.ActionEvent evt) {                                       
    	System.out.println("lishi");
        new InterfaceHistory(expHistory);
    } 
    private void seeHistoryMouseClicked(java.awt.event.MouseEvent evt) {     
    }                                       

    private void aboutMouseClicked(java.awt.event.MouseEvent evt) {                                   
        // TODO add your handling code here:
    }                                  

    private void expTableMouseClicked(java.awt.event.MouseEvent evt) {                                      
        // TODO add your handling code here:
    	
    	
    	String nameTmp = (String)expTable.getValueAt(expTable.getSelectedRow(), 0);
    	//测试
    	String[] temp = new String[5];
    	for(int i = 0; i<=expInfoV.size()-1; i++){
    		if(nameTmp.equals(((String[])expInfoV.elementAt(i))[0])){
    			temp[0] = ((String[])expInfoV.elementAt(i))[0];//名字
    			temp[1] = ((String[])expInfoV.elementAt(i))[1];//完成情况
    			//String[] strTmp = ((String[])expInfoV.elementAt(i))[2].split("/");//日期
    			//temp[3] = strTmp[0] + "年" + strTmp[1] + "月" +strTmp[2] +"日" + strTmp[3] + "时";
    			temp[3] = ((String[])expInfoV.elementAt(i))[2];//日期
    			temp[2] = ((String[])expInfoV.elementAt(i))[3];//成绩
    			temp[4] = ((String[])expInfoV.elementAt(i))[4];//编译信息
    			break;
    		}
    		
    	}
    	if(evt.getClickCount() == 2)
    		new InterfaceExp(temp,personalInfo.getNumber()+"\\experiments\\"+expInfo[expTable.getSelectedRow()][0]);
    }                                     

    public void sync()//将矢量内的内容同步到数组
    {
    	expInfo = new String[expInfoV.size()][4];
    	for(int i = 0; i<=expInfoV.size()-1; i++){
			expInfo[i][0] = ((String[])expInfoV.elementAt(i))[0];//实验名
			expInfo[i][1] = ((String[])expInfoV.elementAt(i))[1];//实验完成情况
			//System.out.print(((String[])exps.elementAt(i))[3]);
			expInfo[i][3] = ((String[])expInfoV.elementAt(i))[2];
			expInfo[i][2] = ((String[])expInfoV.elementAt(i))[3];//成绩
			//expInfo[i][4] = ((String[])expInfoV.elementAt(i))[4];
			}
    	System.out.println("expInfo-----"+expInfo.length);
    }
    public void reflash()
    {
	  	DefaultTableModel b = (DefaultTableModel) expTable.getModel();//、、、、、、、、、、、、、、、、、、、实验列表的修改在这里
	  	int n = b.getRowCount()-1;
	  	for(int i = 0; i<=n; i++){
	  		b.removeRow(0);
	  		System.out.println("删除----"+i);
	  	}
	  	for(int i = 0; i<=expInfo.length-1; i++){
	  		
	  		Vector temp = new Vector();
		  	temp.add(expInfo[i][0]);System.out.println("添加----"+expInfo[i][0]);
		  	temp.add(expInfo[i][1]);
		  	temp.add(expInfo[i][2]);
		  	temp.add(expInfo[i][3]);
		  	b.addRow(temp);
	  	}
	  	jScrollPane1.setVisible(false);
	  	jScrollPane1.setVisible(true);
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
    }

    // Variables declaration - do not modify                     
    private javax.swing.JMenuItem about;
    private javax.swing.JMenuItem exit;
    private javax.swing.JTable expTable;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JPopupMenu.Separator jSeparator1;
    private javax.swing.JMenuItem modify;
    private javax.swing.JLabel pic;
    private javax.swing.JMenuItem seeHistory;
    // End of variables declaration                
    private String experiment;
    private ClientSocket client;
    private PersonalInfo personalInfo;
    private String[][] expInfo;
    private Vector expInfoV;
    private Vector expHistory;
    private Vector shudian;
	@Override
	public void actionPerformed(ActionEvent arg0) {
		String choice = arg0.getActionCommand();
		if(choice.equals("自定义实验")){
			//自定实验
			try {
				client.send("012");//请求实体文件
				client.send("自定义实验");
			} catch (Exception e2) {
				// TODO Auto-generated catch block
				e2.printStackTrace();
			}
			File newTemp = new File(personalInfo.getNumber()+"\\temp");
			try {
				if(newTemp.exists())
					new DeleteFile(personalInfo.getNumber()+"\\temp");
			} catch (IOException e2) {
				// TODO Auto-generated catch block
				e2.printStackTrace();
			}
			newTemp = new File(personalInfo.getNumber()+"\\temp");
			newTemp.mkdirs();
			newTemp = new File(personalInfo.getNumber()+"\\temp\\"+((String[])shudian.elementAt(shudian.size()-1))[1]+".vhd");
			try {
				newTemp.createNewFile();
			} catch (IOException e1) {
				// TODO Auto-generated catch block
				e1.printStackTrace();
			}
			try {
				new InterfaceCdOther((String[])shudian.elementAt(shudian.size()-1),personalInfo,this,client);
			} catch (IOException e) {
				// TODO Auto-generated catch block
				e.printStackTrace();
			}
			this.setVisible(false);
			
			return;
		}
		for(int i = 0; i<=shudian.size()-1; i++){
			if(arg0.getActionCommand() == ((String[])shudian.elementAt(i))[0]){
				experiment = arg0.getActionCommand();
				System.out.println(experiment);
				try {
					client.send("012");//请求实体文件
					client.send(experiment);
				} catch (Exception e2) {
					// TODO Auto-generated catch block
					e2.printStackTrace();
				}
				File newTemp = new File(personalInfo.getNumber()+"\\temp");
				newTemp.deleteOnExit();
				newTemp = new File(personalInfo.getNumber()+"\\temp");
				newTemp.mkdirs();
				newTemp = new File(personalInfo.getNumber()+"\\temp\\"+((String[])shudian.elementAt(i))[1]+".vhd");
				try {
					newTemp.createNewFile();
				} catch (IOException e1) {
					// TODO Auto-generated catch block
					e1.printStackTrace();
				}
				try {
					new InterfaceCoding((String[])shudian.elementAt(i),personalInfo,this,client);
				} catch (IOException e) {
					// TODO Auto-generated catch block
					e.printStackTrace();
				}
				this.setVisible(false);
			}
		}
	}
}

